name = "Placeholder Modpack"
author = "Stevenbf"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03fe3c2d8f001d75e54f3ba77a49474c9c21c307402493923620d637954e8f39"

[versions]
forge = "47.1.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
