name = "Placeholder Modpack"
author = "Stevenbf"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b01d8f5ef8996b4fb4b14284a9fedb2a35829e1f494f947ea0cc8eef762bf07e"

[versions]
forge = "47.1.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
