name = "Placeholder Modpack"
author = "Stevenbf"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2ef25a3527770a2735f9d88fe078416df7d2ee9202fa1a88cee31cd1c61ed4b"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
