name = "Placeholder Modpack"
author = "Stevenbf"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba1e6886b505086fa5f2305295b8e547e1223ea6c8dc49af7329cbdb255c1bd6"

[versions]
forge = "47.1.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
