name = "Placeholder Modpack"
author = "Stevenbf"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80e74478a828a2fb2f83b46c1573a4b13e5e91f5d887f37923a391be13d0a971"

[versions]
forge = "47.1.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
