name = "Placeholder Modpack"
author = "Stevenbf"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "001899b76fcc05ce812be37ad72b17f60ffcd77c1e51611a5bfd337ed62248d1"

[versions]
forge = "47.1.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
