name = "Placeholder Modpack"
author = "Stevenbf"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49cfd13363ab9d1168003231674233c45fc11fff691fb1ad24ed7bc58459567b"

[versions]
forge = "47.1.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
