name = "Placeholder Modpack"
author = "Stevenbf"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34ab0bbd072a6fa3299d14c155ab3f1b98409a9cb511a0daaf0ba73fcc66d289"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
